#!/bin/bash
#Auth: Glad
#Date 11/01/2022
#How to install and configure SonarQube on CentOS 7
#This process need to be run as a regular user (Sonarqube doesnt work when you start it as root user).

#Java 11 installation

yum update -y

yum install java-11-openjdk-devel -y
yum install java-11-openjdk -y

#Download SonarQube latest versions on your server

cd /opt
yum install wget -y
wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.3.0.51899.zip
unzip /opt/sonarqube-9.3.0.51899.zip
unzip /opt/sonarqube-9.3.0.51899.zip

chown -R vagrant:vagrant /opt/sonarqube-9.3.0.51899
cd /opt/sonarqube-x.x/bin/linux-x86-64 
 ./sonar.sh start
 
 echo "Installation successfull"

 #Connect to SonaQube
 #Connect to the SonarQube server through the browser. It uses port 9000.

